Repository fergarcat/multiclass_prediction_obesity_risk, pull requests merged in 2025-05, with the labels that each got.

#46 Feature/docs
  docs/informe-obesidad.docx
  docs/requerimiento-obesidad.docx
Labels: documentation

#58 feat(EDA NB): remove preprocessing cell
  data/eda/EDA_obesity_risk.ipynb
Labels: EDA

#87 Feature/modeling
  data/modeling/Models_benchmarking.ipynb
  data/modeling/benchmarks.py
  data/modeling/pipeline_utils.py
  tests/test_benchmaks.py
  tests/test_kaggle_download.py
  tests/test_pipeline_utils_test.py
Labels: modelo
